# Generated by Django 3.2.8 on 2021-10-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contaxt_date',
            new_name='contact_date',
        ),
    ]
